### ISSUE TITLE
User Story - Create Contact Us Page

### ISSUE THREAD

**Issue by Anthonyrajlucas** [Anthonyrajlucas/django-anto-restaurant-booking-system#5]
EPIC: <Create Contact Us Page>

As a **customer**, I want to **contact** the restaurant **using the contact us page.**

**Acceptance Criteria**

- [x] The page should cover the address.
- [x] The page should cover the timings and contact numbers.
- [x] The page should cover the Google map.
- [x] The Page should cover event details.

**Task**

- [x] Create frontend UI for the Contact Us page.
- [x] Develop a style for the html page.
