### ISSUE TITLE
USER STORY Create a navigation menu

### ISSUE THREAD

**Issue by Anthonyrajlucas** [Anthonyrajlucas/django-anto-restaurant-booking-system#6]
EPIC: <Create a navigation menu>

As **a user**, I can **a navigation menu** so that **I can easily navigate through the website page.**

**Acceptance Criteria**

- [ ] The navigation menu is clear and intuitive.
- [ ] Relevant information of the restaurant such as name, contact us, menu, booking, and login section.

**Task**

- [ ] Create a navigation menu.
- [ ] Add restaurant name, contact us, menu, booking, and login section.
