### ISSUE TITLE
USER STORY - User Sign up/Login

### ISSUE THREAD

**Issue by Anthonyrajlucas** [Anthonyrajlucas/django-anto-restaurant-booking-system#7]
EPIC: <User Sign up/Login>

As **a user**, I can **Sign up and Login to my account** so that ** I can enjoy the full benefits the website has to offer.**

**Acceptance Criteria**

- [ ] The user can successfully sign up.
- [ ] The user can successfully login to/logout from his/her account.
- [ ] The user could be authenticated using email and password.

**Task**

- [ ] Implement 'Sign Up/Login' feature using django-allauth module.
- [ ] Create Sign 'Up/Login' page.
- [ ] Create Sign 'Up/Login' page.
